description = "Sample builder that uses ubi Node.js extension to support Node.js apps"

[[buildpacks]]
uri = "docker://gcr.io/paketo-buildpacks/nodejs:1.4.0"
version = "1.4.0"

[lifecycle]
version = "0.17.0-pre.2"

[[order]]
[[order.group]]
id = "paketo-buildpacks/nodejs"
version = "1.4.0"

[[extensions]]
id = "redhat-runtimes/nodejs"
version = "0.0.1"
uri = "file://./ubi-nodejs-extension"

[[order-extensions]]
[[order-extensions.group]]
id = "redhat-runtimes/nodejs"
version = "0.0.1"

[stack]
id = "ubi8-paketo"
build-image = "quay.io/midawson/ubi8-paketo-build"
run-image = "quay.io/midawson/ubi8-paketo-run"