include:
 - # Red Hat UBI Builder image packaging: Node.js, Quarkus and Java buildpacks
   builder-image: paketobuildpacks/builder-ubi8-base:0.1.1

   # Version needed >= 0.30 to be able to use lifecycle >= 0.17 and to play with extensions
   pack_cli_version: "v0.37.0"

   # Quarkus version, branch to be cloned
   quarkus_version: "3.22"
   quarkus_samples_repo: "https://github.com/quarkusio/quarkus-quickstarts.git"
   repo_subpath: "getting-started"

   # Changed ['11', '17'] to '17' as shipwright job reports:
   # Error: The template is not valid. .github/workflows/shipwright.yaml (Line: 34, Col: 25): A sequence was not expected
   java: "21"

   # Shipwright and Tekton parameters
   tekton-version: "v1.0.0"
   tekton-client-version: "0.40.0"
   # Don't support array -> Run kubectl apply -f https://github.com/tektoncd/pipeline/releases/download/Array/release.yaml
   shipwright-version: "v0.15.6"

   # Buildpacks parameters
   lifecycle-image: "buildpacksio/lifecycle:0.20.9"
   run-image: "paketobuildpacks/run-ubi8-base:0.0.114"
   build-image: "paketobuildpacks/build-ubi8-base:0.0.114"
   insecure-registries: "my-gitea-http.gitea.svc.cluster.local:3000"

   # Kind parameter
   kind_sha_commit: "main"

   # Idpbuilder
   idpbuilder_version: "v0.9.0"
