include:
 - # DEPRECATED: New ubuntu image built top of jammy
   # builder-image: "paketobuildpacks/builder-jammy-tiny:0.0.211"

   # Red Hat UBI Builder image packaging: Node.js, Quarkus and Java buildpacks
   builder-image: "paketocommunity/builder-ubi-base:0.0.92"

   # Version needed >= 0.30 to be able to use lifecycle >= 0.17 and to play with extensions
   pack_cli_version: "v0.35.1"

   # Quarkus java parameter
   quarkus_version: "3.9.5"

   # Changed ['11', '17'] to '17' as shipwright job reports:
   # Error: The template is not valid. .github/workflows/shipwright.yaml (Line: 34, Col: 25): A sequence was not expected
   java: "17"

   # Shipwright and Tekton parameters
   tekton-version: "v0.61.1"
   tekton-client-version: "0.38.1"
   # Don't support array -> Run kubectl apply -f https://github.com/tektoncd/pipeline/releases/download/Array/release.yaml
   shipwright-version: "v0.12.0"

   # Buildpacks parameters
   lifecycle-image: "buildpacksio/lifecycle:0.20.1"
   run-image: "paketocommunity/run-ubi-base:0.0.77"
   build-image: "paketocommunity/build-ubi-base:0.0.77"

   # Kind parameter
   kind_sha_commit: "main"