include:
 - # New ubuntu image built top of jammy
   builder-image: 'paketobuildpacks/builder-jammy-tiny:0.0.175'

   # Version needed >= 0.30 to be able to use lifecycle 0.17 and to play with extensions
   pack_cli_version: 'v0.30.0-rc1'