= How to build a runtime using buildpack
:icons: font
:revdate: {docdate}
:toc: left
:toclevels: 2
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://github.com/redhat-buildpacks/testing/actions/workflows/quarkus.yaml[image:https://github.com/redhat-buildpacks/testing/actions/workflows/quarkus.yaml/badge.svg[]]
https://github.com/redhat-buildpacks/testing/actions/workflows/pack.yaml[image:https://github.com/redhat-buildpacks/testing/actions/workflows/pack.yaml/badge.svg[]]
https://github.com/redhat-buildpacks/testing/actions/workflows/tekton.yaml[image:https://github.com/redhat-buildpacks/testing/actions/workflows/tekton.yaml/badge.svg[]]
https://github.com/redhat-buildpacks/testing/actions/workflows/shipwright.yaml[image:https://github.com/redhat-buildpacks/testing/actions/workflows/shipwright.yaml/badge.svg[]]
https://github.com/redhat-buildpacks/testing/pulse[image:https://img.shields.io/github/commit-activity/m/redhat-buildpacks/testing[]]

== Introduction

The goal of this project is to test/validate different approaches to build a runtime using:

* <<1-quarkus-buildpacks,Quarkus Java Buildpack>>
* <<2-pack-client,Pack>> client
* <<3-tekton,Tekton>> Pipeline
* <<4-shipwright,Shipwright>>
* <<5-rhtap,Red Hat Trusted Application Pipeline (aka RHTAP)>>

== Project Testing Matrix

The following table details the versions of the different tools/images used within the GitHub e2e workflows
or examples of this project.

This project currently verifies the following scenario:

- link:.github/workflows/quarkus.yaml[Quarkus HelloWord build using Java Buildpack library]
- link:.github/workflows/pack.yaml[Quarkus HelloWord build using Pack client]
- link:.github/workflows/pack_nodejs.yaml[Node.js Hello using extension and pack]
- link:.github/workflows/tekton.yaml[Quarkus HelloWorld & Tekton Pipeline]
- link:.github/workflows/shipwright.yaml[Quarkus HelloWorld & Shipwright]

|===
| Tool/Image | Version | Tested | Note

| Lifecycle
| https://github.com/buildpacks/lifecycle/releases/tag/v0.20.7[0.20.7]
| Yes
| -

| Platform
| https://github.com/buildpacks/spec/blob/platform/0.13/platform.md[0.13.0]
| Yes
| -

| Pack client
| https://github.com/buildpacks/pack/releases/tag/v0.37.0[v0.37.0]
| Yes
| -

| Java Buildpack library
| https://github.com/snowdrop/java-buildpack-client/tree/0.0.14[0.0.14]
| Yes
| Support platform from 0.4 to 0.13 !

| Quarkus Buildpack
| https://quarkus.io/guides/container-image#buildpack[3.22]
| Yes
| - !

| Paketo Build base ubi image
| https://github.com/paketo-buildpacks/ubi8-base-stack/releases/tag/v0.0.111[0.0.111]
| Yes
| Base image to be used to build

| Paketo Run base ubi image
| https://github.com/paketo-buildpacks/ubi8-base-stack/releases/tag/v0.0.111[0.0.111]
| Yes
| Base image to be used to run a container

| Paketo community UBI builder
| https://github.com/paketo-buildpacks/builder-ubi8-base/releases/tag/v0.0.202[0.0.202]
| Yes
| Include Node.js, Quarkus Java Buildpacks.

| Paketo Node.js Extension for ubi
| https://github.com/paketo-buildpacks/ubi-nodejs-extension/releases/tag/v1.3.1[1.3.1]
| Yes
| -

| Paketo Java Extension for ubi
| https://github.com/paketo-community/ubi-java-extension/releases/tag/v0.2.0[0.2.0]
| Yes
| -
|===

== 0. Prerequisites

- Podman desktop installed and running
- https://cnoe.io/docs/reference-implementation/idpbuilder[IDPlatform running kind] (>= 0.10)
- https://tekton.dev/docs/cli/#installation[Tekton CLI] (>= 0.40)
- Create an `.env` with the different variables to be used and source it

[NOTE]
====
For local tests, we suggest to create a kubernetes `kind` cluster and a container registry using the `idpbuilder` tool:
====

[,bash]
----
idpbuilder create --dev-password --name buildpack
----

As the registry that we will access uses the HTTPS protocol and a self-signed certificate, it is then needed to define it as an insecure registry using the following command (when you use podman) in order to avoid a TLS error as the certificate has been signed by an unknown authority:
[,bash]
----
echo 'printf "\n[[registry]]\nlocation = \""gitea.cnoe.localtest.me:8443\""\ninsecure = true\n" >> /etc/containers/registries.conf' |  podman machine ssh --username root --
podman machine stop; podman machine start
----

== 1. Quarkus Buildpacks

First, create a `Quarkus Hello` example using the following maven command executed in a terminal.

[,bash]
----
mvn io.quarkus.platform:quarkus-maven-plugin:3.21.3:create \
  -DprojectGroupId=dev.snowdrop \
  -DprojectArtifactId=quarkus-hello \
  -DprojectVersion=1.0 \
  -DplatformVersion=3.22.0.CR1 \
  -Dextensions='resteasy,kubernetes,buildpack'
----

Test the project locally:
[,bash]
----
cd quarkus-hello
mvn compile quarkus:dev
----

In a separate terminal, curl the HTTP endpoint

[,bash]
----
curl http://localhost:8080/hello
----

To build the container image, do the build using the ubi builder image `paketobuildpacks/builder-ubi8-base:0.0.122` and pass `+BP_***+` env variables in order to configure properly the Quarkus buildpack build process:

[,bash]
----
mvn clean package \
 -Dquarkus.container-image.image=gitea.cnoe.localtest.me:8443/giteaadmin/quarkus-hello:1.0 \
 -Dquarkus.container-image.build=true \
 -Dquarkus.container-image.push=true \
 -Dquarkus.buildpack.jvm-builder-image=paketobuildpacks/builder-ubi8-base:0.0.202 \
 -Dquarkus.buildpack.builder-env.BP_JVM_VERSION="21" \
 -Dquarkus.buildpack.use-daemon=true \
 -Dquarkus.buildpack.registry-user."gitea.cnoe.localtest.me:8443"=giteaAdmin \
 -Dquarkus.buildpack.registry-password."gitea.cnoe.localtest.me:8443"=developer
----

[NOTE]
====
To get the debug messages and configure the logger `slf4j`, add the following quarkus properties:

[,bash]
----
 ...
 -Dquarkus.buildpack.log-level=debug \
 -Dorg.jboss.logging.provider=slf4j \
 -Dorg.slf4j.simpleLogger.log.io.quarkus.container.image.buildpack.deployment=DEBUG \
 -Dorg.slf4j.simpleLogger.log.dev.snowdrop.buildpack.docker=DEBUG
----

Next, start the container and curl the endpoint

[,bash]
----
podman run -i --rm -p 8080:8080 gitea.cnoe.localtest.me:8443/giteaadmin/quarkus-hello:1.0
curl http://localhost:8080/hello
----

== 2. Pack client

To validate this scenario top of the existing quarkus-hello project, we will use the https://buildpacks.io/docs/tools/pack/[pack client].

[,bash]
----
podman rmi $REGISTRY_HOST/giteaadmin/quarkus-hello:1.0
pack build $REGISTRY_HOST/giteaadmin/quarkus-hello:1.0 \
     --builder paketobuildpacks/builder-ubi8-base:latest \
     --volume $HOME/.m2:/home/cnb/.m2:rw \
     -e BP_JVM_VERSION=21
----

Next, start the container and curl the endpoint `+curl http://localhost:8080/hello+`

[,bash]
----
podman run -i --rm -p 8080:8080 gitea.cnoe.localtest.me:8443/giteaadmin/quarkus-hello:1.0
----

== 3. Tekton

To use https://tekton.dev/[Tekton], it is needed to have a k8s cluster (>= 1.27), and a container registry.
To install it like the dashboard, we will rely on the `idplatform` cluster we created using the `idpbuilder` tool

[,bash]
----
idpbuilder create --dev-password --name buildpack \
  -p https://github.com/ch007m/my-idp-packages//tekton
----

When the platform is ready, you should be able to access the Tekton UI at the following address: `https://tekton-ui.cnoe.localtest.me:8443/`. You can verify if Tekton has been well installed using the Argo CD console: `https://argocd.cnoe.localtest.me:8443/`

Deploy now the different tasks or resources that we need to build an application:

[,bash]
----
kubectl apply -f https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-clone/0.9/git-clone.yaml
----

[WARNING]
====
Don't install the buildpacks-phases version 0.2 from the https://github.com/tektoncd/catalog/tree/main/task/buildpacks-phases[catalog] as it is outdated and do not work with lifecycle >= 1.17 supporting the `extension` mechanism
====

[,bash]
----
kubectl delete -f https://raw.githubusercontent.com/redhat-buildpacks/catalog/main/tekton/task/buildpacks-phases/01/buildpacks-phases.yaml
kubectl delete -f https://raw.githubusercontent.com/redhat-buildpacks/catalog/main/tekton/task/buildpacks-extension-phases/01/buildpacks-extension-phases.yaml

kubectl apply -f https://raw.githubusercontent.com/redhat-buildpacks/catalog/main/tekton/task/buildpacks-phases/01/buildpacks-phases.yaml
kubectl apply -f https://raw.githubusercontent.com/redhat-buildpacks/catalog/main/tekton/task/buildpacks-extension-phases/01/buildpacks-extension-phases.yaml
----

Create a dockercfg's secret using the gitea registry credentials to access it and link it to the ServiceAccount that Tekton will use.

[,bash]
----
kubectl apply -f k8s/tekton/secret-dockercfg.yml
kubectl apply -f k8s/tekton/sa-with-reg-creds.yml
----

Create a PVC
[,bash]
----
kubectl apply -f k8s/tekton/ws-pvc.yml
----

Set next the following variables:

[,bash]
----
IMAGE_NAME=<CONTAINER_REGISTRY>/<ORG>/quarkus-hello
BUILDER_IMAGE=<PAKETO_BUILDER_IMAGE_OR_YOUR_OWN_BUILDER_IMAGE>
----

It is time to create a `Pipelinerun` to build the Quarkus application

[,bash]
----
IMAGE_NAME=my-gitea-http.gitea.svc.cluster.local:3000/giteaadmin/quarkus-hello

#BUILDER_IMAGE=paketobuildpacks/builder-ubi8-base:0.0.202 -> Use 0.0.203 when out as it fixes the issue to access gitea using HTTP protocol
BUILDER_IMAGE=ghcr.io/matejvasek/builder-ubi8-base:latest
CNB_BUILD_IMAGE=paketobuildpacks/build-ubi8-base:0.0.111
CNB_RUN_IMAGE=paketobuildpacks/run-ubi8-base:0.0.111
CNB_INSECURE_REGISTRIES=my-gitea-http.gitea.svc.cluster.local:3000

echo "apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: buildpacks-phases
  labels:
    app.kubernetes.io/description: buildpack-pipeline-run
spec:
  taskRunTemplate:
    serviceAccountName: sa-with-creds
  params:
    - name: gitRepo
      value: https://github.com/quarkusio/quarkus-quickstarts.git
    - name: sourceSubPath
      value: getting-started
    - name: AppImage
      value: $IMAGE_NAME
    - name: cnbBuilderImage
      value: $BUILDER_IMAGE
    - name: cnbBuildImage
      value: $CNB_BUILD_IMAGE
    - name: cnbLogLevel
      value: $CNB_LOG_LEVEL
    - name: cnbRunImage
      value: $CNB_RUN_IMAGE
    - name : cnbInsecureRegistries
      value: $CNB_INSECURE_REGISTRIES
    - name: cnbBuildEnvVars
      value:
        - BP_JVM_VERSION=21
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/redhat-buildpacks/catalog.git
      - name: revision
        value: main
      - name: pathInRepo
        value: tekton/pipeline/buildpacks/01/buildpacks.yaml
  workspaces:
    - name: creds-ws
      secret:
        secretName: dockercfg
    - name: source-ws
      subPath: source
      persistentVolumeClaim:
        claimName: ws-pvc
    - name: cache-ws
      subPath: cache
      persistentVolumeClaim:
        claimName: ws-pvc" | kubectl apply -f -
----

Follow the execution of the pipeline using the dashboard: `https://tekton-ui.cnoe.localtest.me:8443/#/namespaces/default/pipelineruns` or using the client: `tkn pipelinerun logs -f`

When the pipelinerun finishes and no error has been reported, then launch the container

[,bash]
----
podman run -i --rm -p 8080:8080 gitea.cnoe.localtest.me:8443/giteaadmin/quarkus-hello
----

== 4. Shipwright

See the project documentation for more information: https://github.com/shipwright-io/build

To use shipwright, it is needed to have a k8s cluster, a container registry and tekton installed (>= v0.48.+)

Next, deploy the release `0.12` of shipwright

[,bash]
----
// kubectl create -f https://github.com/shipwright-io/build/releases/download/v0.12.0/release.yaml
kubectl create -f https://github.com/shipwright-io/build/releases/download/v0.15.6/release.yaml
----

Apply the following hack to create a self-signed certificate on the cluster, otherwise the shipwright webhook will fail to start
[,bash]
----
curl --silent --location https://raw.githubusercontent.com/shipwright-io/build/v0.15.6/hack/setup-webhook-cert.sh | bash
----

Next, install the `Buildpacks BuildStrategy` using the following command:

[,bash]
----
kubectl delete -f k8s/shipwright/clusterbuildstrategy.yml
kubectl apply -f k8s/shipwright/clusterbuildstrategy.yml
----

Create a `Build` CR using as source the Quarkus Getting started repository:
====

[,bash]
----
kubectl delete -f k8s/shipwright/build.yml
kubectl apply -f k8s/shipwright/build.yml
----

To check the `Build` resource you just created, execute the following command:

[,bash]
----
kubectl get build
NAME                      REGISTERED   REASON      BUILDSTRATEGYKIND      BUILDSTRATEGYNAME   CREATIONTIME
buildpack-quarkus-build   True         Succeeded   ClusterBuildStrategy   buildpacks          43s
----

Create a configMap containing the self-signed certificate of the registry
[,bash]
----
kubectl get secret -n default idpbuilder-cert -ojson | jq -r '.data."ca.crt"' | base64 -d > ca.cert

kubectl delete configmap certificate-registry
kubectl create configmap certificate-registry \
  --from-file=ca.cert
----

To trigger a `BuildRun` do this:

[,bash]
----
kubectl delete buildrun -lbuild.shipwright.io/name=buildpack-quarkus-build
kubectl delete -f k8s/shipwright/pvc.yml
kubectl delete -f k8s/shipwright/sa.yml

kubectl create -f k8s/shipwright/sa.yml
kubectl create -f k8s/shipwright/pvc.yml
kubectl create -f k8s/shipwright/buildrun.yml
----

Wait until your `BuildRun` is completed, and then you can view it as follows:

[,bash]
----
kubectl get buildrun -lbuild.shipwright.io/name=buildpack-quarkus-build
NAME                               SUCCEEDED   REASON      STARTTIME   COMPLETIONTIME
buildpack-quarkus-buildrun-fbs84   True        Succeeded   103s        25s
----

When the task is finished and no error is reported, then launch the container

[,bash]
----
podman run -i --rm -p 8080:8080 gitea.cnoe.localtest.me:8443/giteaadmin/quarkus-hello
----

Enjoy !

## Troubleshooting section

The instructions described hereafter should help to resolve the issue when lifecycle access the gitea registry inside a pod
[,bash]
----
#set -x BUILDER paketobuildpacks/builder-ubi8-base:0.0.202
set -x BUILDER ghcr.io/matejvasek/builder-ubi8-base:latest

echo "Test 1 using patched lifecycle, insecure registry define & CNB_REGISTRY_AUTH - OK"
podman run -it \
  -e CNB_PLATFORM_API=0.13 \
  -e CNB_REGISTRY_AUTH='{"https://gitea.cnoe.localtest.me:8443": "Basic Z2l0ZWFBZG1pbjpkZXZlbG9wZXI="}' \
  --network=host \
  $BUILDER \
  /cnb/lifecycle/analyzer \
  -log-level=debug \
  -layers=/layers \
  -run-image=paketobuildpacks/run-ubi8-base:0.0.111 \
  -uid=1002 \
  -gid=1000 \
  -insecure-registry=gitea.cnoe.localtest.me:8443 \
  gitea.cnoe.localtest.me:8443/giteaadmin/quarkus-hello

podman run -it \
  -e CNB_PLATFORM_API=0.13 \
  -v $(pwd)/auth.json:/home/cnb/.docker/config.json:ro \
  --network=host \
  $BUILDER \
  /cnb/lifecycle/analyzer \
  -log-level=debug \
  -layers=/layers \
  -run-image=paketobuildpacks/run-ubi8-base:0.0.111 \
  -uid=1002 \
  -gid=1000 \
  -insecure-registry=gitea.cnoe.localtest.me:8443 \
  gitea.cnoe.localtest.me:8443/giteaadmin/quarkus-hello
----
Using a pod
[,bash]
----
kubectl delete secret/dockercfg
kubectl create secret generic dockercfg \
  --from-file=.dockerconfigjson=$(pwd)/.tmp/dockercfg.json \
  --type=kubernetes.io/dockerconfigjson

kubectl delete -f $(pwd)/.tmp/task-pod-1.yaml; kubectl apply -f $(pwd)/.tmp/task-pod-1.yaml
----

