apiVersion: shipwright.io/v1alpha1
kind: Build
metadata:
  name: buildpack-quarkus-build
spec:
  source:
    url: https://github.com/quarkusio/quarkus-quickstarts
    contextDir: getting-started
  strategy:
    name: buildpacks
    kind: ClusterBuildStrategy
  output:
    image: kind-registry.local:5000/snowdrop/quarkus-hello:latest
    credentials:
      name: registry-creds