apiVersion: shipwright.io/v1alpha1
kind: Build
metadata:
  name: buildpack-quarkus-build
spec:
  source:
    url: https://github.com/quarkusio/quarkus-quickstarts
    contextDir: getting-started
    revision: 3.2.3.Final
  paramValues:
    #
    - name: SOURCE_SUBPATH
      value: getting-started
    - name: CNB_PLATFORM_API
      value: "0.12"
    - name: CNB_BUILDER_IMAGE
      value: paketobuildpacks/builder-jammy-tiny:0.0.211
    - name: CNB_LIFECYCLE_IMAGE
      value: buildpacksio/lifecycle:0.18.2
    - name: RUN_IMAGE
      value: paketobuildpacks/run-jammy-tiny:latest
    - name: APP_IMAGE
      value: kind-registry.local:5000/quarkus-hello
    - name: PROCESS_TYPE
      value: ""
    - name: ENV_VARS
      values:
        - value: BP_NATIVE_IMAGE=false
        - value: BP_MAVEN_BUILT_ARTIFACT=target/quarkus-app/lib/ target/quarkus-app/*.jar target/quarkus-app/app/ target/quarkus-app/quarkus/
        - value: BP_MAVEN_BUILD_ARGUMENTS=package -DskipTests=true -Dmaven.javadoc.skip=true -Dquarkus.package.type=fast-jar
  strategy:
    name: buildpacks
    kind: ClusterBuildStrategy
  output:
    image: kind-registry.local:5000/snowdrop/quarkus-hello:latest
    credentials:
      name: registry-creds