apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: buildpacks
spec:
  params:
    - name: gitRepo
      value: https://github.com/nodeshift-starters/nodejs-rest-http
    - name: AppImage
      value: quay.io/ch007m/nodejs-pack-test
    - name: cnbBuilderImage
      value: paketobuildpacks/builder-ubi8-base:latest
    - name: cnbBuildImage
      value: paketobuildpacks/build-ubi8-base:latest
    - name: cnbRunImage
      value: paketobuildpacks/run-ubi8-base:latest
    - name: cnbBuildEnvVars
      value: []
  serviceAccountName: sa-with-creds
  workspaces:
    - name: source-ws
      subPath: source
      persistentVolumeClaim:
        claimName: ws-pvc
    - name: cache-ws
      subPath: cache
      persistentVolumeClaim:
        claimName: ws-pvc
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/redhat-buildpacks/catalog.git
      - name: revision
        value: main
      - name: pathInRepo
        value: tekton/pipeline/buildpacks/01/buildpacks.yaml