---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: buildpacks
spec:
  params:
    # RHTAP Params
    - name: git-url
      value: https://github.com/quarkusio/quarkus-quickstarts.git
    - name: path-context
      value: getting-started
    - name: output-image
      value: quay.io/ch007m/quarkus-tekton-hello
    # Others
    - name: gitRepo
      value: https://github.com/quarkusio/quarkus-quickstarts.git
    - name: sourceSubPath
      value: getting-started
    - name: AppImage
      value: quay.io/ch007m/quarkus-tekton-hello
    - name: cnbBuilderImage
      value: paketobuildpacks/builder-jammy-tiny:0.0.211
    - name: cnbBuildImage
      value: paketobuildpacks/build-ubi8-base:0.0.77
    - name: cnbRunImage
      value: paketobuildpacks/run-ubi8-base:0.0.77
    - name: cnbBuildEnvVars
      value:
        - "BP_NATIVE_IMAGE=false"
        - "BP_MAVEN_BUILT_ARTIFACT=target/quarkus-app/lib/ target/quarkus-app/*.jar target/quarkus-app/app/ target/quarkus-app/quarkus/"
        - "BP_MAVEN_BUILD_ARGUMENTS=package -DskipTests=true -Dmaven.javadoc.skip=true -Dquarkus.package.type=fast-jar"
  serviceAccountName: sa-with-creds
  workspaces:
    - name: source-ws
      subPath: source
      persistentVolumeClaim:
        claimName: ws-pvc
    - name: cache-ws
      subPath: cache
      persistentVolumeClaim:
        claimName: ws-pvc
    - name: workspace
      persistentVolumeClaim:
        claimName: ws-pvc
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/redhat-buildpacks/catalog.git
      - name: revision
        value: main
      - name: pathInRepo
        value: tekton/pipeline/rhtap/01/pipeline-buildpacks.yaml