apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  name: buildpack-quarkus-build
spec:
  source:
    type: Git
    git:
      url: "https://github.com/quarkusio/quarkus-quickstarts"
      revision: 3.8.3
    contextDir: getting-started
  paramValues:
    #
    - name: SOURCE_SUBPATH
      value: getting-started
    - name: CNB_LOG_LEVEL
      value: "info"
    - name: CNB_EXPERIMENTAL_MODE
      value: "warn"
    #- name: CNB_USER_ID
    #  value: "1002"
    #- name: CNB_GROUP_ID
    #  value: "1002"
    - name: CNB_BUILDER_IMAGE
      value: paketocommunity/builder-ubi-base:0.0.92
    - name: RUN_IMAGE
      value: paketobuildpacks/run-jammy-tiny:latest
    - name: APP_IMAGE
      value: kind-registry.local:5000/quarkus-hello
    - name: PROCESS_TYPE
      value: ""
    - name: ENV_VARS
      values:
        - value: BP_NATIVE_IMAGE=false
  strategy:
    name: buildpacks
    kind: ClusterBuildStrategy
  output:
    image: kind-registry.local:5000/snowdrop/quarkus-hello:latest