name: "Reusable workflow parsing the YAML config and share the matrix using GITHUB_OUTPUT"

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      matrix:
        description: "Matrix of configurations"
        value: ${{ jobs.generate-json-matrix.outputs.matrix }}

jobs:
  generate-json-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3

      - id: set-matrix
        name: Convert the YAML config JSON and pass it as matrix's value to matrix GITHUB_OUTPUT
        run: |
          #echo "matrix=$(yq -P -o=json ${{ github.workspace }}/config.yml | jq -c .)" >> $GITHUB_OUTPUT
          matrix="matrix=$(yq -P -o=json ${{ github.workspace }}/config.yml | jq -c .)"
          echo $matrix
          echo $matrix >> $GITHUB_OUTPUT