name: "Job parsing the config and share it using GITHUB_OUTPUT"

on:
  workflow_call:  # allow this workflow to be called from other workflows

jobs:
  configure-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
      - id: set-matrix
        run: |
          echo "matrix=$(yq -P -o=json ${{ github.workspace }}/config.yml | jq -c .)" >> $GITHUB_OUTPUT