name: "Test using Pack CLI"
on: [workflow_call]  # allow this workflow to be called from other workflows

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
      - name: yaml-to-json
        run: |
          yq -P -o=json ${{ github.workspace }}/config.yml > ${{ github.workspace }}/config.json
      - id: set-matrix
        run: |
          echo "matrix=$(jq -c . < ${{ github.workspace }}/config.json)" >> $GITHUB_OUTPUT