name: "Test using Java Buildpacks client"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '*.adoc'        # Ignores .adoc files at the root of the repository
      - '*.md'          # Ignores .md files at the root of the repository
      - '**/*.md'       # Ignores .md files within subdirectories
jobs:
  configure-matrix:
    uses: ./.github/workflows/configure.yaml

  linux-jvm-build:
    name: Linux - JVM build
    needs: configure-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.configure-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          check-latest: true

      #- name: Setup Container Registry
      #  uses: Sgitario/setup-container-registry@v1

      - name: Remove podman
        run: |
          echo "Remove podman as docker is installed by default within the ubuntu image"
          sudo systemctl stop podman.socket
          sudo systemctl stop podman

          sudo apt-get remove podman

      - name: Get Runner IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Print Runner IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }}
          echo ${{ steps.ip.outputs.ipv6 }}

      - name: Run a container registry
        run: |
          mkdir ~/registry
          cd ~/registry
          mkdir data

          RUNNER_IP=${{ steps.ip.outputs.ipv4 }}
          echo "IP address: $RUNNER_IP"

          docker run -d --restart unless-stopped \
              --network=host \
              -p "5000:5000" \
              -e REGISTRY_HTTP_ADDR=0.0.0.0:5000 \
              -e REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data \
              -v $PWD/data:/data \
               registry:2

          cp /etc/hosts local_hosts
          echo "$RUNNER_IP registry" >> local_hosts
          cat local_hosts
          sudo cp local_hosts /etc/hosts

      - name: Try to access the registry
        run: |
          echo "Check the containers running"
          docker ps

          RUNNER_IP=${{ steps.ip.outputs.ipv4 }}
          echo "IP address: $RUNNER_IP"

          echo "cat /etc/hosts file"
          cat /etc/hosts

          docker pull alpine
          docker tag alpine registry:5000/alpine
          docker push registry:5000/alpine

      - name: "Test the Java Buildpacks Sample using as builder image: ${{ matrix.builder-image }}"
        run: |
          CONTAINER_NAME=quarkus-jvm-hello
          CONTAINER_IMAGE=registry:5000/$CONTAINER_NAME:1.0

          DOCKER_HOST=unix:///var/run/docker.sock

          SAMPLES_DIR=$(pwd)/.github/samples
          QUARKUS_HELLO_DIR=$(pwd)/quarkus-quickstarts/getting-started

          # Checkout the java project to be build
          git clone --depth 1 --branch ${{ matrix.quarkus_version }} https://github.com/quarkusio/quarkus-quickstarts.git

          # Compile the BuildMe sample
          cd $SAMPLES_DIR/build-me
          mvn -B compile

          # Set the mandatory env variables
          export PROJECT_PATH=$QUARKUS_HELLO_DIR
          export IMAGE_REF=$CONTAINER_IMAGE
          export BP_JVM_VERSION="21"
          export CNB_BUILDER_IMAGE=${{ matrix.builder-image }}
          export CNB_INSECURE_REGISTRIES="registry:5000"

          # Build the image and push it to the container registry
          mvn exec:java

      - name: "Checking the image published"
        run: |
          # yamllint disable-line rule:new-line-at-end-of-file
          docker image inspect $CONTAINER_IMAGE
