name: "Test Nodejs ubi extension with Pack CLI"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - nodejs-ubi-extension
jobs:
  linux-pack-build:
    if: contains(github.event.head_commit.message, 'pack_nodejs_test')
    name: Linux - Pack CLI build
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    builder-image: [ 'paketobuildpacks/builder:tiny' ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Container Registry
        uses: Sgitario/setup-container-registry@v1
        with:
          host: container-registry.local

      - name: Install Pack
        # Version installed: 0.29 (June 2023)
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
          sudo apt-get update
          sudo apt-get install pack-cli

      - name: Test Nodejs UBI extension
        run: |
          CONTAINER_NAME=quarkus-pack-hello
          CONTAINER_IMAGE=$CONTAINER_REGISTRY_URL/$CONTAINER_NAME:1.0
          #BUILDER_PATH=.github/nodejs_ubi_builder.toml

          # Checkout
          git clone https://github.com/paketo-community/ubi-nodejs-extension.git

          echo "Enable experimental features in pack"
          pack config experimental true
          
          echo "Build the detect and generate binaries of the extension"
          ${{ github.workspace }}/ubi-nodejs-extension/scripts/build.sh
          
          echo "Creating the builder image and push it"
          BUILDER_PATH=./builder.toml
          
          cat <<EOF > builder.toml
          description = "Sample builder that uses ubi Node.js extension to support Node.js apps"
  
          [[buildpacks]]
          uri = "docker://gcr.io/paketo-buildpacks/nodejs:1.4.0"
          version = "1.4.0"
          
          [lifecycle]
          version = "0.17.0-pre.2"
          
          [[order]]
          [[order.group]]
          id = "paketo-buildpacks/nodejs"
          version = "1.4.0"
          
          [[extensions]]
          id = "redhat-runtimes/nodejs"
          version = "0.0.1"
          uri = "file:///${{ github.workspace }}/ubi-nodejs-extension"
          
          [[order-extensions]]
          [[order-extensions.group]]
          id = "redhat-runtimes/nodejs"
          version = "0.0.1"
          
          [stack]
          id = "ubi8-paketo"
          build-image = "quay.io/midawson/ubi8-paketo-build"
          run-image = "quay.io/midawson/ubi8-paketo-run"
          EOF
          
          pack builder create $CONTAINER_IMAGE --config $BUILDER_PATH --publish
          
          echo "Build the nodejs app"
          git clone https://github.com/nodeshift-starters/nodejs-rest-http.git
          pack build test-app --path ./nodejs-rest-http --env BP_NODE_VERSION=16 --builder $CONTAINER_IMAGE --network host -v 
          
          echo "Run the nodejs rest http application ..."
          docker run -p 8080:8080 test-app