name: "Test using Quarkus Buildpack extension"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '*.adoc'        # Ignores .adoc files at the root of the repository
      - '*.md'          # Ignores .md files at the root of the repository
      - '**/*.md'       # Ignores .md files within subdirectories
jobs:
  configure-matrix:
    uses: ./.github/workflows/configure.yaml

  linux-jvm-build:
    name: Linux - JVM build
    needs: configure-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.configure-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          check-latest: true

      - name: Setup Container Registry
        uses: Sgitario/setup-container-registry@v1

      - name: Test Quarkus Getting Started using ${{ matrix.builder-image }}
        run: |
          CONTAINER_NAME=quarkus-jvm-hello
          CONTAINER_IMAGE=$CONTAINER_REGISTRY_URL/$CONTAINER_NAME:1.0

          # Checkout
          git clone --depth 1 --branch ${{ matrix.quarkus_version }} https://github.com/quarkusio/quarkus-quickstarts.git
          cd quarkus-quickstarts/getting-started

          # Add quarkus-container-image-buildpack extension
          mvn quarkus:add-extension -Dextensions="container-image-buildpack"

          # Build image and push to the container registry
          mvn package -B \
            -Dquarkus.container-image.image=$CONTAINER_IMAGE \
            -Dquarkus.buildpack.jvm-builder-image=${{ matrix.builder-image }} \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true

          # Test application
          ../../.github/testGreetingApplication.sh $CONTAINER_NAME $CONTAINER_IMAGE