name: "Test using Quarkus Container Image Buildpack extension"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  linux-jvm-build:
    name: Linux - JVM build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
        builder-image: [ 'paketobuildpacks/builder:tiny' ]
    steps:
      - uses: actions/checkout@v3
      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          check-latest: true

      - name: Setup Container Registry
        uses: Sgitario/setup-container-registry@v1

      - name: Test Quarkus Getting Started using ${{ matrix.builder-image }}
        run: |
          CONTAINER_NAME=quarkus-jvm-hello
          CONTAINER_IMAGE=$CONTAINER_REGISTRY_URL/$CONTAINER_NAME:1.0

          # Checkout
          git clone https://github.com/quarkusio/quarkus-quickstarts.git
          cd quarkus-quickstarts/getting-started

          # Add quarkus-container-image-buildpack extension
          mvn quarkus:add-extension -Dextensions="container-image-buildpack"

          # Build image and push to the container registry
          mvn package \
            -Dquarkus.container-image.image=$CONTAINER_IMAGE \
            -Dquarkus.buildpack.jvm-builder-image=${{ matrix.builder-image }} \
            -Dquarkus.buildpack.builder-env.BP_NATIVE_IMAGE="false" \
            -Dquarkus.buildpack.builder-env.BP_MAVEN_BUILT_ARTIFACT="target/quarkus-app/lib/ target/quarkus-app/*.jar target/quarkus-app/app/ target/quarkus-app/quarkus/" \
            -Dquarkus.buildpack.builder-env.BP_MAVEN_BUILD_ARGUMENTS="package -DskipTests=true -Dmaven.javadoc.skip=true -Dquarkus.package.type=fast-jar" \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true

          # Test application
          ../../.github/testGreetingApplication.sh $CONTAINER_NAME $CONTAINER_IMAGE