name: "Test using Shipwright"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  linux-shipwright-build:
    name: Linux - Shipwright build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
        tekton-version: [ 'v0.47.0' ]
        shipwright-version: [ 'v0.11.0' ]
        tekton-client-version: [ '0.31.0']
        builder-image: [ 'paketobuildpacks/builder:0.1.361-tiny' ]
        lifecycle-image: [ 'buildpacksio/lifecycle:0.16.3' ]
        run-image: [ 'paketobuildpacks/run:tiny' ]
    steps:
      - uses: actions/checkout@v3
      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          check-latest: true

      - name: Setup Kind with Registry
        run: |
          curl -s -L "https://raw.githubusercontent.com/snowdrop/k8s-infra/main/kind/kind.sh" | bash -s install --registry-name kind-registry.local

      - name: Setup Tekton & Shipwright
        run: |
          kubectl apply -f https://github.com/tektoncd/pipeline/releases/download/${{ matrix.tekton-version }}/release.yaml
          kubectl wait deployment -n tekton-pipelines tekton-pipelines-controller --for condition=Available=True --timeout=90s
          kubectl wait deployment -n tekton-pipelines tekton-pipelines-webhook --for condition=Available=True --timeout=90s
          
          kubectl apply -f https://github.com/shipwright-io/build/releases/download/${{ matrix.shipwright-version }}/release.yaml
          kubectl wait deployment -n shipwright-build shipwright-build-controller --for condition=Available=True --timeout=90s
          
          wget https://github.com/tektoncd/cli/releases/download/v${{ matrix.tekton-client-version }}/tektoncd-cli-${{ matrix.tekton-client-version }}_Linux-64bit.rpm
          sudo rpm -Uvh tektoncd-cli-${{ matrix.tekton-client-version }}_Linux-64bit.rpm

      - name: Test Quarkus Getting Started using ${{ matrix.builder-image }}
        run: |
          CONTAINER_NAME=quarkus-shipwright-hello
          CONTAINER_IMAGE=kind-registry.local:5000/$CONTAINER_NAME:1.0
          
          kubectl create -f ./k8s/shipwright/unsecured/pvc.yml
          kubectl apply  -f ./k8s/shipwright/unsecured/clusterbuildstrategy.yml
          kubectl apply  -f ./k8s/shipwright/unsecured/build.yml
          kubectl create -f ./k8s/shipwright/unsecured/buildrun.yml
          
          # Wait for the build
          BUILDRUN_NAME=$(kubectl get buildrun -lbuild.shipwright.io/name=buildpack-quarkus-build -oname)
          kubectl wait --for=condition=Succeeded --timeout=600s buildrun/$BUILDRUN_NAME

          # Test application
          .github/testGreetingApplication.sh $CONTAINER_NAME localhost:5000/$CONTAINER_NAME:1.0

      - name: Print BuildRun logs no matter if it fails or success
        if: failure() || success()
        run: |
          BUILDRUN_NAME=$(kubectl get buildrun -lbuild.shipwright.io/name=buildpack-quarkus-build -oname)
          tkn taskrun logs $BUILDRUN_NAME
